### ISSUE TITLE
Planification/Submit: Rendering of Round partial fails.

### ISSUE THREAD

**Issue by 3three** [3three/envielogistique#11]
```
  Rendered planification/_round_partial.html.erb (3.5ms)
Completed 500 Internal Server Error in 98724ms

ActionView::Template::Error (undefined method `state' for true:TrueClass):
    1: <div class="round_capsule">
    2: <table class="rounds_list_item state_<%= round.state_name unless round.state.nil? %> <%= 'droppable' if round.state_name == 'nouveau' %>" id="round_<%= round.id %>">
    3: 
    4:   <tr>
    5: 
  app/views/planification/_round_partial.html.erb:2:in `_app_views_planification__round_partial_html_erb__2464379683353494245_70126608956940'
  app/controllers/planification_controller.rb:124:in `block (2 levels) in create'
  app/controllers/planification_controller.rb:120:in `create'


  Rendered /Library/Ruby/Gems/2.0.0/gems/actionpack-4.0.4/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.8ms)
  Rendered /Library/Ruby/Gems/2.0.0/gems/actionpack-4.0.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (1.8ms)
  Rendered /Library/Ruby/Gems/2.0.0/gems/actionpack-4.0.4/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (31.6ms)
```

**Comment by 3three** [comment]
Well and truly resolved.
