### ISSUE TITLE
Planification/Round Submission fails because of unexpected popup from SAP...

### ISSUE THREAD

**Issue by 3three** [3three/envielogistique#3]
```
I, [2015-04-16T15:07:47.846849 #42564]  INFO -- : Generating Data structures (Round > Bordereau > Service Request) based on Service Requests (Eco-Systèmes)...
I, [2015-04-16T15:08:09.617264 #42564]  INFO -- : 
STARTING submission of the Round information
I, [2015-04-16T15:08:09.617966 #42564]  INFO -- : Confirming Service Request 6000659495...
I, [2015-04-16T15:08:17.182215 #42564]  INFO -- : Confirming Service Request 6000659495...
I, [2015-04-16T15:08:17.736646 #42564]  INFO -- : Completed 500 Internal Server Error in 30129ms
F, [2015-04-16T15:08:17.738293 #42564] FATAL -- : 
Selenium::WebDriver::Error::UnhandledAlertError (unexpected alert open
  (Session info: chrome=42.0.2311.90)
  (Driver info: chromedriver=2.12.301326 (093c7e07b4a916b690e784b0374c7f618f1ea4be),platform=Mac OS X 10.10.2 x86_64)):
  app/controllers/concerns/planification_concern.rb:466:in `confirm_service_request'
  app/controllers/concerns/planification_concern.rb:145:in `block in submit_round'
  app/controllers/concerns/planification_concern.rb:144:in `each'
  app/controllers/concerns/planification_concern.rb:144:in `submit_round'
  app/controllers/concerns/planification_concern.rb:71:in `validate_round'
  app/controllers/planification_controller.rb:118:in `create'
```

**Comment by 3three** [comment]
Tentative solution: I was not waiting for the Loading Spinner after clicking "Confirm". Based on past experience, this should solve the issue.

We now wait for it, so the problem should be gone.

**Comment by 3three** [comment]
I've also added a wait for the "Search" button to appear as a proxy for the page being fully loaded. This seems to have eliminated the problem.

**Comment by 3three** [comment]
Long resolved.
